# Generated by Django 5.2.1 on 2025-06-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='decisioncategory',
            options={'verbose_name': 'Категория решений', 'verbose_name_plural': 'Категории решений'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='userchoicesession',
            options={'verbose_name': 'Сессия выбора', 'verbose_name_plural': 'Сессии выбора'},
        ),
        migrations.AlterModelOptions(
            name='usercustomoption',
            options={'verbose_name': 'Пользовательский вариант', 'verbose_name_plural': 'Пользовательские варианты'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='decisioncategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='decisioncategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='decisioncategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.decisioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='userchoicesession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.decisioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userchoicesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userchoicesession',
            name='method',
            field=models.CharField(choices=[('coin', 'Монетка'), ('wheel', 'Колесо фортуны'), ('yesno', 'Да или нет'), ('drum', 'Барабан'), ('custom', 'Свои варианты')], default='custom', max_length=50, verbose_name='Метод выбора'),
        ),
        migrations.AlterField(
            model_name='userchoicesession',
            name='result',
            field=models.CharField(blank=True, max_length=200, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='userchoicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usercustomoption',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_options', to='app.userchoicesession', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='usercustomoption',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст варианта'),
        ),
    ]
