# Generated by Django 5.2.1 on 2025-06-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_decisioncategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinhistory',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='spinhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spinhistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='decisioncategory',
            options={'verbose_name': 'Категория решений', 'verbose_name_plural': 'Категории решений'},
        ),
        migrations.RemoveField(
            model_name='decisioncategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='decisioncategory',
            name='is_user_created',
        ),
        migrations.RemoveField(
            model_name='decisioncategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='decisioncategory',
            name='user',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.decisioncategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.DeleteModel(
            name='DecisionOption',
        ),
        migrations.DeleteModel(
            name='SpinHistory',
        ),
    ]
