# Generated by Django 5.2.1 on 2025-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usercategory_usercategoryoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Слаг'),
        ),
    ]
