# Generated by Django 5.2.1 on 2025-06-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usercategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategoryoption',
            name='category',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserCategoryOption',
        ),
    ]
